name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.19', '1.20' ]
    steps:
      - name: チェックアウト
        uses: actions/checkout@v3

      - name: Go のセットアップ
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: 依存ライブラリの取得
        run: go mod download

      - name: テストの実行とカバレッジレポート生成
        run: go test -v -coverprofile=coverage.out ./...

      - name: Codecov へのカバレッジレポートアップロード
        uses: codecov/codecov-action@v3
        with:
          file: coverage.out